name: Validate Nix Flake
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
  push:
    paths:
      - "**.nix"
      - "**.lock"
      - ".github/workflows/check.yml"
      - ".github/actions/**/*"

# Minimal permissions; workflows run on GitHub-hosted runners only.
permissions: {}

jobs:
  check-flake:
    name: Check (${{ matrix.system }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux
          - os: macos-latest
            system: aarch64-darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Use the explicitly passed ref if provided, otherwise the current ref name
          ref: ${{ inputs.ref || github.ref_name }}
          persist-credentials: false

      # Install Nix on the GitHub runner (no Lix)
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14
      # Optional but recommended: enable binary caches for faster CI
      - name: Enable Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      # Run flake checks with experimental features enabled explicitly,
      # and disallow IFD for reproducible evaluation.
      - name: Check Flake
        shell: bash
        run: |
          nix --extra-experimental-features 'nix-command flakes' \
            flake check --option allow-import-from-derivation false
