name: Nix Autofix

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"  # Mondays at 06:00 UTC
  push:
    branches: [ main, master ]

permissions:
  contents: write
  pull-requests: write

jobs:
  autofix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Enable Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Create working branch
        shell: bash
        run: |
          branch="ci/nix-autofix"
          git checkout -B "$branch"

      - name: Format with nixfmt-rfc-style
        shell: bash
        run: |
          git ls-files -z '*.nix' > nix_files.z
          xargs -0 -r nix run --extra-experimental-features 'nix-command flakes' \
            nixpkgs#nixfmt-rfc-style -- < nix_files.z

      - name: Apply statix fixes (safe)
        shell: bash
        run: |
          nix run --extra-experimental-features 'nix-command flakes' \
            nixpkgs#statix -- fix

      - name: Remove dead code with deadnix --edit
        shell: bash
        run: |
          nix run --extra-experimental-features 'nix-command flakes' \
            nixpkgs#deadnix -- --edit .

      - name: Commit changes
        shell: bash
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "chore(nix): autofix via nixfmt/statix/deadnix"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ci/nix-autofix
          title: "chore(nix): autofix via nixfmt/statix/deadnix"
          commit-message: "chore(nix): autofix via nixfmt/statix/deadnix"
          body: |
            Automated PR applying:
            - `nix run nixpkgs#nixfmt-rfc-style`
            - `nix run nixpkgs#statix -- fix`
            - `nix run nixpkgs#deadnix -- --edit`
          labels: [automation, maintenance]
``
