name: Bump Flake Inputs

on:
  workflow_dispatch:
  schedule:
    - cron: "3 0 * * *" # run daily at 00:03 UTC

permissions: {}

jobs:
  update-lockfile:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    outputs:
      pr: ${{ steps.pr.outputs.pull-request-url }}
      branch: ${{ steps.pr.outputs.pull-request-branch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      # Install Nix (no Lix)
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3.11.3
      # Optional but recommended: enable binary caches for faster CI
      - name: Enable Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      # Update flake.lock via Determinate Systems action
      - name: Update Lockfile
        id: pr
        uses: DeterminateSystems/update-flake-lock@v27
        with:
          commit-msg: "flake.lock: update all inputs"
          pr-title: "flake.lock: update all inputs"
          branch: update-flake-inputs
          pr-body: |
            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```

  check:
    name: Check Flake
    needs: update-lockfile
    uses: ./.github/workflows/check.yml
    with:
      ref: ${{ needs.update-lockfile.outputs.branch }}

  check-lock:
    name: Check Lock
    needs: update-lockfile
    uses: ./.github/workflows/check-lock.yml
    with:
      ref: ${{ needs.update-lockfile.outputs.branch }}

  merge:
    name: Merge Pull Request
    needs: [update-lockfile, check, check-lock]
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Merge Pull Request
        run: gh pr merge --rebase --auto --delete-branch "$PR"
        env:
          GH_TOKEN: ${{ github.token }}
          PR: ${{ needs.update-lockfile.outputs.pr }}
